from crewai import Task
from agents import professor, visualizer, quizmaster

def create_study_tasks(topic_or_content: str):
    """
    Creates and returns the sequential tasks for the study crew.
    It takes the dynamic input (either a typed topic or extracted file text) 
    from the Streamlit app.
    """
    
    # Check if the input is an image path
    is_image = topic_or_content.startswith("[IMAGE_PATH]")
    
    # Task 1: The Professor explains the core concept
    explain_task = Task(
        description=(
            f"Analyze the following material: '{topic_or_content}'.\n"
            f"{'IMPORTANT: This is an image path. You MUST use your Analyze Educational Image tool with this path to read its contents first!' if is_image else ''}\n"
            "1. Identify the 3 most important core concepts.\n"
            "2. Write a clear, beginner-friendly explanation using analogies.\n"
            "3. Format this as the 'Concept Breakdown' section."
        ),
        expected_output="A detailed, beginner-friendly explanation of the core concepts formatted in Markdown. If the input was an image, the explanation should be based on the image's contents.",
        agent=professor
    )

    # Task 2: The Visualizer creates the image
    visualize_task = Task(
        description=(
            "Based on the Professor's explanation, identify the most difficult or abstract concept.\n"
            "1. Write a 1-2 sentence highly descriptive prompt visualizing this concept (e.g., 'A 3D isometric diagram showing data flowing from...').\n"
            "2. Pass this prompt to the 'Generate Concept Image' tool.\n"
            "3. The tool will return a Markdown image link. You MUST output this exact image link in your final response."
        ),
        expected_output="The exact Markdown image link generated by the tool, preceded by a 1-sentence caption.",
        agent=visualizer
    )

    # Task 3: The Quizmaster compiles everything
    compile_task = Task(
        description=(
            "You are responsible for the final Study Guide.\n"
            "1. Take the Professor's 'Concept Breakdown'.\n"
            "2. Take the Visualizer's image link and embed it immediately after the breakdown.\n"
            "3. Generate a 'Practice Quiz' section with 3 multiple-choice questions based on the material, including an Answer Key at the very bottom.\n"
            "4. Combine everything into a single, beautifully structured Markdown document."
        ),
        expected_output="A complete Markdown study guide containing the explanation, the generated image, and a practice quiz.",
        agent=quizmaster
    )

    return [explain_task, visualize_task, compile_task]