from crewai import Task
from agents import professor, visualizer, quizmaster

def create_study_tasks(topic_or_content: str, mode="default"):
    """
    Creates and returns the sequential tasks for the study crew.
    Allows for dynamic task routing based on the selected mode.
    """
    
    is_image = "[IMAGE_PATH]" in topic_or_content
    image_instruction = ""
    if is_image:
        image_instruction = "CRITICAL: The prompt contains an [IMAGE_PATH]. You MUST use the 'Analyze Educational Image' tool on it."

    if mode == "flashcards":
        return [
            Task(
                description=f"Analyze the following material: '{topic_or_content}'. {image_instruction}\nExtract exactly the key terms and concepts and format them strictly as a Markdown structured list of Flashcards (Term: Definition). Do not add any conversational padding.",
                expected_output="A Markdown list of study flashcards.",
                agent=professor
            )
        ]
        
    elif mode == "quiz":
        return [
            Task(
                description=f"Analyze the following material: '{topic_or_content}'. {image_instruction}\nGenerate a complete, challenging Interactive Quiz (5 multiple choice, 2 short answer) based on the context. Append an Answer Key at the very bottom.",
                expected_output="A complete Markdown practice quiz with answer key.",
                agent=quizmaster
            )
        ]

    elif mode == "syllabus":
        return [
            Task(
                description=f"Analyze the following material: '{topic_or_content}'. {image_instruction}\nGenerate a comprehensive, week-by-week syllabus and structured learning blueprint for this topic.",
                expected_output="A Markdown syllabus outlining a learning curriculum.",
                agent=professor
            )
        ]

    # --- DEFAULT FULL MODE ---
    explain_task = Task(
        description=(
            f"Analyze the following material: '{topic_or_content}'.\n"
            f"{image_instruction}\n"
            "1. Identify the 3 most important core concepts.\n"
            "2. Write a clear, beginner-friendly explanation using analogies.\n"
            "3. Format this as the 'Concept Breakdown' section."
        ),
        expected_output="A detailed, beginner-friendly explanation of the core concepts formatted in Markdown.",
        agent=professor
    )

    visualize_task = Task(
        description=(
            "Based on the Professor's explanation, identify the structural components.\n"
            "1. Write clean Graphviz DOT syntax representing a BLOCK DIAGRAM (rankdir=LR).\n"
            "   - CRITICAL: Node IDs MUST be strictly alphanumeric with NO spaces.\n"
            "   - CRITICAL: Text labels must be in double-quotes.\n"
            "2. Pass this DOT code to the 'Generate Concept Image' tool.\n"
            "3. Return the exact Markdown image link outputted by the tool."
        ),
        expected_output="The exact Markdown image link generated by the tool.",
        agent=visualizer
    )

    compile_task = Task(
        description=(
            "1. Take the Professor's breakdown and the Visualizer's image link.\n"
            "2. Generate a 'Practice Quiz' section with 3 MCQs and an Answer Key.\n"
            "3. Compile everything into a beautiful final Markdown Study Guide."
        ),
        expected_output="A complete Markdown study guide.",
        agent=quizmaster
    )

    return [explain_task, visualize_task, compile_task]